import "./globals.css";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {ReactNode} from "react";
import Notificaction from "@/components/notificaction";
import AuthSessionProvider from "@/components/AuthSessionProvier";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: ReactNode;
}

export default function RootLayout({children}: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthSessionProvider>
          {children}
          <Notificaction />
        </AuthSessionProvider>
      </body>
    </html>
  );
}
